<style>
p{    text-align:justify;     font-family: "Helvetica Neue",Helvetica,Arial,sans-serif !important;}
h4 {
    color: greenyellow;
}
</style>

<!-- header bg -->
		<div class="inner-bg">
			<div class="container">
				<div class="inner-text">
					<h1 class="wow slideInDown" data-wow-delay="300ms" data-wow-duration="1500ms">Terms & <span>Conditions</span></h1>
					<ul>
						<li><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a></li>
						<li>/</li>
						<li><a href="#">Terms & Conditions</a></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- header bg end -->
	</header>
	<section class="list-store">
		<!-- list-store -->
		<div class="container">
		    <!---->
		    <div class="row">	
            <div class="col-md-12">
                 						<!-- title -->
					<div class="tilte">
						<h2>TERMS & <span>CONDITIONS</span></h2>
					</div>
					<!-- /title -->
				</div></div>
		    <!---->
			<P  class="ab">
				<div class="col-sm-12 col-md-12">
					<!-- contact-info -->
		<div class="contact-info"style="    margin-top: 0px !important;">
		    <!---->
		    <h4>Acceptance of Terms and Conditions</h4>

<p>By using www.dcountnow.com (hereinafter mentioned as the “Website” or “Dcount Now”), the user agrees to the present terms and conditions, unconditionally, without any curtailment/ restriction, that we Dcount Now have provided hereunder for the use of the present Website. In the event that you do not wish to agree to the laid down terms and conditions (hereinafter mentioned as the “Agreement”), we request you to kindly not use the present website. </p>


<h4>General</h4>
<p>Dcount   Now  is a website providing a range of services thereto providing a platform where we list offers for local services, products , goods, services and more which are made available by us through other sellers ,owned and operated by DMISROF  ANALYTICS PRIVATE LIMITED .  (Company name) (mentioned hereinafter as the “Company” ) through the internet , consisting of information services, content and transaction capabilities which have been provided by the Company, its associates, subsidiaries with whom it has any form of business which includes but does not limit third parties that provide services with respect to production, distribution of content, creation or distribution of content of the Website (Third Party Content Providers), third parties that act/ function on behalf of the Company. By sharing your information or registering on/ with www.dcountnow.com, the Dcount Now app and any other affiliates you explicitly agree to be contacted/ communicated to vide  personnel vide calls, SMS’s, emails in relation to our services, promotional offers, deals and bargains, updates of new services and other services. </p>
<p>The User by subscribing to the services which are provided by Dcount Now, further unconditionally agrees to be contacted by Dcount Now or any of its merchants, affiliates, associates and / or assigns for regular updates relating to the services, status of their requests, new and / or promotional offers and other information, which Dcount Now in its sole discretion may deem fit and appropriate to send to the User(s) and the same in any manner will not be treated as breach of any privacy or rights of the User(s). </p> 
<p>This present Agreement sets forth the terms and conditions that apply in order to use the present Website by the User. The rights to use this Website is for the purpose of the individual User and is not transferable to any other person or entity in any manner whatsoever. The User shall be responsible for protecting the confidentiality of User's own password(s), if any. </p>
<p>The User further understands and acknowledges that, although the Internet is considered a secure environment, there are possibilities of interruptions in service or events which are in no manner in the control of Dcount Now, and Dcount Now shall not be held accountable for any information or date lost in the process of transmission of Information on the internet. Although it is Dcount Now’s endeavour to make the Website accessible at all times, the Website may be unavailable on rare occasions for any reason which include, without any limitation, routine maintenance. The User(s) understand and acknowledge that in light of circumstances both which are within and outside the control of Dcount Now, access to the Website may be occasionally unavailable. Dcount Now further reserves the right, having sole discretion, to terminate the access to any or all Dcount Now websites and the related services or any portion thereof at any time, without notice. Dcount Now shall also have the right at any point of time to change or discontinue any aspect or feature of the Website, including, but not limited to, content, graphics, deals, offers, settings, hours of availability and equipment needed for access or use. Furthermore, Dcount Now may discontinue and/or disseminating any portion of information, may make changes or eliminate any transmission method and may change transmission speeds or other signal characteristics based on requirement. </p>

<h4>Modified Terms</h4>
<p>Dcount Now reserves the right to discontinue or modify any of our Terms of Use and/or our Privacy Policy at any point of time as we deem necessary or fit without prior notification to the User. Such alterations may include, among other things, the addition of certain fees/charges. Dcount Now, therefore, suggests to the User that the User re-read this important notice containing our Terms of Use and Privacy Policy from time to time in order to stay informed as to any such changes. If Dcount Now makes changes to our Terms of Use and Privacy Policy and the User continues to use our Website, they will have been assumed to have implicitly agreed to the amended Terms of Use and Privacy Policy. Unless specified otherwise, any such deletions, alterations or modifications shall be effective immediately upon Dcount Now 's posting thereof. Any use of the Website by the User after such notice shall be deemed to constitute as acceptance by the User of such modifications. </p>


<h4>Equipment</h4>
<p>It shall be the sole responsibility of the User for obtaining and maintaining all telephone, computer hardware and other equipment needed for access to and use of this Website and all charges related thereto. Dcount Now shall not be liable for any damages to the User's equipment resulting from the use of this Website. </p>


<h4>Registration</h4>
<p>In order to utilize certain parts of the Website, the User may be required to complete a registration process and establish an account with Dcount Now ("Account").The User will further represent and warrant that all information provided by you to Dcount Now is current, accurate, and complete, and that you will maintain the accuracy and completeness of this information on a prompt, timely basis. </p>

<h4>Password and Security</h4>
<p>At the time of registering the user on the Website, the User may receive or establish a user name and one or more passwords. The User(s) themselves are solely responsible for maintaining the confidentiality and security of their own password(s) and Account(s). the User must understand and agree that they are individually and fully responsible for all actions and postings made from their Account(s). Any accounts they create are not transferrable. The User agrees to notify Dcount Now immediately if they become aware of any unauthorized use of their Account(s). </p>

<h4>User Conduct</h4>
<p>This Website and any individual websites or merchant-specific, city/ state-specific at present or hereinafter contained within or otherwise available through any external hyperlinks with our Website (the "Mini sites") are private property. All interactions/ communication on this Website and/or the Minisites must comply with these Terms of Use. The User shall not post or transmit through this present Website and/or the Minisites any material which is in violation or which infringes upon the rights of others and/or any material which is in any manner unlawful, defamatory, abusive, threatening, invasive of privacy or rights of publicity, obscene, profane, vulgar, or otherwise considered objectionable and/or which encourages or prompts conduct that would constitute as a criminal offense, gives rise to any  civil liability or otherwise violate any laws, or which, without Dcount Now's express prior, written approval, contains advertising or any other form of solicitation with respect to products or services in any manner. Any conduct by a User that in Dcount Now's exclusive discretion is considered breach of the Terms of Use or which restricts or inhibits any other User from using or enjoying this Website and/or any of the Minisites is strictly prohibited. The User shall not use this Website and/or any of the Minisites to advertise or perform any commercial, political, religious or non-commercial solicitation, which is inclusive of, but not limited to, the solicitation of the users of this Website and/or the Mini sites to become users of other online or offline services directly or indirectly competitive or potentially competitive with Dcount Now. </p>
<p>The aforementioned provisions of this Section 7 applies equally to and are for the benefit of Dcount Now, its Business Associates, subsidiaries,  and Third Party Content Providers, and each shall have the right to defend and enforce such provisions directly or on its own behalf. </p>


<h4>Purchase and Redemption of Dcount Now Coupons</h4>
<p>Dcount Now provides its user with an opportunity to avail value deals and bargains from a number of select merchants and sellers, including but not limited to restaurants and other various services, with which Dcount Now has an association at discounted prices by issuance of coupons that can be redeemed up to a certain validity period from outlets of the Institutions. In order to purchase such Dcount Now Coupons, the User would be required to create an account on the Website. The same will be required so we can provide the User with easy access to print and maintain the Users orders, view past purchases / transactions and modify preferences and choices. By placing an order on this Website, the User makes an offer to us to purchase Dcount Now Coupons for buying / availing specific products and/or services which you have selected based on Dcount Now´s standard terms and conditions and institution-specific restrictions on these Terms of Use. All Dcount Now coupons are promotional coupons and shall be subject to Standard Terms and Conditions and Specific Terms and Conditions. Dcount Now Coupons are issued on behalf of the Institutions (Sellers/ Service Providers) and only such Institutions (Sellers/ Service Providers) , to the exclusion of Dcount Now, shall be responsible for any and all injuries, illnesses, damages, charges, expenses, claims, liabilities and costs suffered by or in respect of a customer, caused in whole or in part by the Institutions (Sellers/ Service Providers) or which arises out of the goods and/or services provided by the Institutions (Sellers/ Service Providers), as well as for any unclaimed property liability arising from unredeemed Dcount Now Coupons. </p>
<p>Promotion codes & subscription packs are not valid on any products, lucky draws & select service deals. </p>


<h4>Standard Terms and Conditions (for Restaurant-Specific Dcount Now Coupons). </h4>
<p>For this specific section, Restaurants herein shall be defined as an Institution that offers food and beverages for sale in its regular business operations, and is making such food and beverages as stated hereinabove, available to purchasers of Dcount Now Coupons. In this respect, the following shall constitute as Standard Terms and Conditions for redeeming Dcount Now Coupons in this respect.</p>
<ul>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>   Dcount Now shall not be held responsible for the quality of services provided by the Restaurant at any point, and the same shall be the sole responsibility of the Restaurant itself. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  No refunds shall be granted for Dcount Now Coupons purchased. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Dcount Now Coupons are redeemable in their entirety only and the same cannot be redeemed in increments. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Furthermore, Dcount Now Coupons can be redeemed only after due verification of the customer which includes, without limiting, matching the unique identification number provided to the User/ customer at the time of purchase of the Dcount Now Coupons. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Validity period for redemption of Dcount Now Coupons is determined by the Restaurants, and shall be specified on Dcount Now Coupons. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Use of Dcount Now Coupons for alcoholic beverages is at the sole discretion of the Restaurant and is further subject to all applicable laws. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  It is further at the discretion of the Restaurant to determine whether Dcount Now Coupons can be combined with any other Restaurant coupons, coupons, third party coupons, or promotions. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Dcount Now Coupons cannot be used for the purpose of taxes, tips or prior balances, unless expressly permitted by the Restaurant. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Dcount Now Coupons are valid for dine-in only unless otherwise expressly mentioned. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  The issuance of restaurant credit is at the sole discretion of the Restaurant. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Neither Dcount Now nor the Restaurant is to be held responsible for lost or stolen Dcount Now Coupons or the reference numbers mentioned on it.
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Reproduction, sale, copying or trade of Dcount Now Coupons is strictly prohibited. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  Any attempted redemption not consistent with these above terms & conditions will render the Dcount Now Coupon void and invalid. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i>  The Dcount Now Coupon will expire on the date specified on coupon. </li>
</ul>

<h4>Standard Terms and Conditions (for other institutions based Dcount Now Coupons). </h4>
<p>The following shall constitute as Standard Terms and Conditions for redeeming Dcount Now Coupons for purchasing goods and/or services from all institutions: </p>
<ul>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Dcount Now shall not be held responsible for the quality of products and/or services provided by the Institution, and the same shall be the sole responsibility of the Institution. </li> 
	<li><i class="fa fa-telegram" aria-hidden="true"></i> No refunds shall be granted to Users for Dcount Now Coupons. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Dcount Now Coupons are redeemable in their entirety only and may not be redeemed in increments. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Dcount Now Coupons can be redeemed only after due verification of the User/ customer including, without limitation, which may include matching the unique identification number provided 
	 to the User at the time of purchase of Dcount Now Coupons. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Dcount Now Coupons will be only applicable to purchase the merchandise sold by the Institution, and will not be applicable to shipping or handling charges. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> The prescribed limit is one (1) Coupon per redemption. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Unless specified by the Institution, only one Coupon can be used per visit. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Issuance of credit is at the sole discretion of the Institution. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Neither Dcount Now nor the Institution will be responsible for stolen or lost Dcount Now Coupons or loss of the reference number mentioned on the coupon. Unless specified by the institution, Dcount Now Coupons cannot be combined with any other gift coupons, coupons, promotions or third party coupons. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Reproduction, sale, copying or trade of Dcount Now Coupons is strictly prohibited. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> Any attempted redemption not consistent with these above terms & conditions will render the Dcount Now Coupon void and invalid. </li>
	<li><i class="fa fa-telegram" aria-hidden="true"></i> The Dcount Now Coupon will expire on the date specified on coupon. </li>
</ul>

<h4>Purchase and Sale of Products and/or Services</h4>
<p>Dcount Now takes no responsibility for the services and/or products for which Dcount Now Coupons may be redeemed by the User. Furthermore, Dcount Now gives no warranty to the Users for aspects such as quality, usability, safety or any other aspect of the product or service for which the Dcount Now Coupon may be redeemed. Dcount Now  shall not be in any manner held responsible or liable for any form of loss, injury, damage or any harm caused to the User(s) by availing the products / services offered through their website or any other affiliate website(s) or services rendered by Dcount Now. Some services for which Dcount Now Coupon(s) can be redeemed are activities that involve potential bodily harm and for those activities Dcount Now takes no responsibility for the service or activity being offered, in as much that the User shall take responsibility for his or her own actions in utilizing the services for which the Dcount Now Coupon can be redeemed. Furthermore, no two marketing promotions on products or services can be combined. Dcount Now requires your permission to send you administrative and promotional emails as a condition of purchase. We will periodically send the User information regarding your account activity and purchases, as well as updates about our products and promotional offers. They can opt out of our promotional emails anytime by clicking the unsubscribe link at the bottom of any of our email correspondences. The details of the same can be found in our Privacy Policy.
</p>
<h4>User Generated Content</h4>
<p>The Website will allow the User to contribute and add value deals. Dcount Now reserves the right to include the value deal contributed by you to the Website or discard it, in its sole discretion. </p>
<p>Dcount Now shall not have any obligation to pre-screen or regularly review all contributed content/ value deal. However, Dcount Now has the absolute right (though not the obligation) to remove, without notice, any content / value deal posted. </p>
<p>By posting any content/ value deal, you represent and warrant (a) you have all right, title, and interest to such posted content/ value deal, including but not limited to any consent, authorization, release, clearance or license from any third party (such as, but not limited to, any release related to rights of privacy or publicity) necessary for you to provide, post, upload, input or submit the posted content, or (b) such posted content/ value deal is in the public domain, or (c) your use of such posted content/ value deal constitutes fair use. You further represent and warrant that posting such content/ value deal does not violate or constitute the infringement of any patent, copyright, trademark, trade secret, right of privacy, right of publicity, moral rights, or other intellectual property right recognized by any applicable jurisdiction of any person or entity, or otherwise constitute the breach of any agreement with any other person or entity. </p>
<p>You also agree not to post any of the following types of content to the Website: (a) adult content, pornography, explicit sexual images, or nude images; (b) content containing explicit, vulgar, or obscene language; (c) content promoting hate, abuse or destructive actions; (d) content promoting illegal activities; or primarily political, religious, psychic, or metaphysical content; (e) content promoting pirated software; (f) content intending for phishing or spreading malware; (g) content that is disparaging of any person or entity; (h) content that is in violation of any law or regulation; or (i) any other content that is or could be considered inappropriate, unsuitable or offensive, all as determined by us. </p>
<p>You shall be liable for any claims , damages or other demands arising due to any content/ value deal posted by you in violation of this clause and agree to indemnify Dcount Now for any claims, damages or other demands arising due to any content/ value deal posted by you. </p>
<h4>Copyright and Trademarks</h4>
<p>Everything located on or in this Website, including the Minisites, is the exclusive property of Dcount Now or used with express permission of the copyright and/or trademark owner. Any violation of this policy may result in a copyright, trademark or other intellectual property right infringement that may subject User to civil and / or criminal penalties. </p>
<p>This Website contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of Dcount Now is protected by copyright as a collective work under the Indian copyright laws. Dcount Now owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. </p>
<p>The User may not publish, modify, participate, transmit in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part in any manner whatsoever. The User is within their right to download / print / save copyrighted material for the User's personal use only. Except as otherwise expressly stated under copyright law, no copying, retransmission, publication, redistribution or commercial exploitation of downloaded material without the express permission of Dcount Now and the copyright owner is permitted. In the event copying, redistribution or publication of copyrighted material is permitted to the User, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. The User acknowledges that they do not acquire any ownership rights by downloading copyrighted material from the Website. All Trademarks that are found within or on the Website or a Web site otherwise owned or operated in conjunction with Dcount Now shall not be deemed to be in the public domain but rather the exclusive property of Dcount Now, unless such site is under license from the Trademark owner thereof in which case such license is for the exclusive benefit and use of Dcount Now, unless otherwise stated. The User acknowledges that they shall not upload, post or otherwise make available on this Website any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. Dcount Now shall not have any express burden or responsibility to provide the User with indications, markings or anything else that may aid the User in determining whether the material in question is copyrighted or trademarked. The User shall be held solely liable for any damage or legal action resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. It is further to be noted that by submitting material to any public area of this Website, the User warrants that the owner of such material has expressly granted Dcount Now the royalty-free, perpetual, irrevocable and non-exclusive right and license to use, publish, modify, adapt, reproduce,  translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. The Users also permits any other User to access, view, store or reproduce the material for that User's personal use. The User hereby grants Dcount Now the right to edit, copy, publish and distribute any material made available on this Website by the User. </p>
<p>The foregoing provisions of Section 14 apply equally to and are for the benefit of Dcount Now, its subsidiaries, Business Associates and Third Party Content Providers and each shall have the right to assert and enforce such provisions directly or on its own behalf. </p>


<h4>Disclaimer of Warranty; Limitation of Liability</h4>
<p>User expressly agrees that use of this website and the minisites is at user's sole risk. neither Dcount Now, its subsidiaries and business associates nor any of their respective employees, agents and third party content providers warrant that use of the website will be uninterrupted or error free; nor do they make any warranty as to (i) the results that may be obtained from use of this website, or (ii) the accuracy, reliability or content of any information, service or merchandise provided through this website or the minisites. </p>
<p>this website and the minisites are made accessible on an "as is" basis without warranties of any kind, either express or implied, including, but not limited to, warranties of title or implied warranties of merchantability or fitness for a particular purpose, other than those warranties which are implied by and incapable of exclusion, restriction or modification under the laws applicable to this agreement. </p>
<p>this disclaimer of liability applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortuous behaviour, negligence, or under any other cause of action. User specifically acknowledges that Dcount Now is not liable for the defamatory, offensive or illegal conduct of other users or third-parties and that the risk of injury from the foregoing rests entirely with user. </p>
<p>In no event shall Dcount Now, or any person or entity involved in creating, producing or distributing this website or the contents hereof, including the minisites and any software, be liable for any damages, including, without limitation, direct, indirect, incidental, special, consequential or punitive damages arising out of the use of or inability to use this website. User hereby acknowledges that the provisions of this section shall apply to all content on this site and the minisites. </p>
<p>in addition to the terms set forth above, neither Dcount Now, nor its subsidiaries and business associates, third party service providers or third party content providers shall be liable regardless of the cause or duration, for any errors, inaccuracies, omissions, or other defects in, or untimeliness or unauthenticity of, the information contained within this website or any of the minisites, or for any delay or interruption in the transmission thereof to the user, or for any claims or losses arising therefrom or occasioned thereby. None of the foregoing parties shall be liable for any third-party claims or losses of any nature, including without limitation lost profits, punitive or consequential damages. </p>
<p>Dcount Now is not responsible for any content that a user, subscriber, or an unauthorized user may post on this website or any of the minisites. Any content that is posted or uploaded that is or may be deemed unsuitable can and may be taken down by Dcount Now. Moreover, Dcount Now reserves the right to edit, change, alter, delete and prohibit any and all content that it, Dcount Now, deems unsuitable. </p>


<h4>Monitoring</h4>
<p>Dcount Now shall have the right, but not the obligation, to monitor the content of the Website at all times, including any chat rooms and forums that may hereinafter be included as part of the Website, to determine compliance with this Agreement and any operating rules established by Dcount Now, as well as to satisfy any applicable law, regulation or authorized government request. Without limiting the foregoing, Dcount Now shall have the right to remove any material that Dcount Now, in its sole discretion, finds to be in violation of the provisions hereof or otherwise objectionable. </p>


<h4>Privacy</h4>
<p>User acknowledges that all discussion for ratings, comments, bulletin board service, chat rooms and/or other message or communication facilities (collectively "Communities") are public and not private communications, and that, therefore, others may read User's communications without User's knowledge. Dcount Now does not control or endorse the content, messages or information found in any Community, and, therefore, Dcount Now specifically disclaims any liability concerning the Communities and any actions resulting from User's participation in any Community, including any objectionable content. Generally, any communication which User posts on the Website (whether in chat rooms, discussion groups, message boards or otherwise) is considered to be non-confidential. If particular web pages permit the submission of communications that will be treated by Dcount Now as confidential, that fact will be stated on those pages. By posting comments, messages or other information on the Website, User grants Dcount Now the right to use such comments, messages or information for promotions, advertising, market research or any other lawful purpose. For more information see Dcount Now's Privacy Policy. </p>


<h4>License Grant</h4>
<p>By posting content/ value deals/ communications on or through this Website, User shall be deemed to have granted to Dcount Now a royalty-free, perpetual, irrevocable & non-exclusive license to copy, transmit, use, reproduce, modify, publish, edit, translate, distribute, perform, display, reformat and incorporate it into a collective work the content/ value deals/ communication alone or as part of other works in any form, media, or technology whether now known or hereafter developed, and to sublicense such rights through multiple tiers of sublicensees. For greater certainty, this means that, among other things, Dcount Now has the right to use any and all ideas you submit (including ideas about our products, services, publications or advertising campaigns) in any manner that we choose, without any notice or obligation to you whatsoever.
</p>

<h4>Indemnification</h4>
<p>User agrees to defend, indemnify and hold harmless Dcount Now, its subsidiaries and Business Associates, and their respective directors, officers, employees and agents from and against all claims and expenses, including attorneys' fees, arising out of the use of this Website and/or the Minisites by User. </p>


<h4>Termination</h4>
<p>Dcount Now may terminate this Agreement at any time. Without limiting the foregoing, Dcount Now shall have the right to immediately terminate any passwords or accounts of User in the event of any conduct by User which Dcount Now, in its sole discretion, considers to be unacceptable, or in the event of any breach by User of this Agreement. All such provisions wherein the context so requires including Sections 13, 14, 17, 18 & 19 will survive termination of this Agreement. </p>

<h4>Third Party Content</h4>
<p>Dcount Now, similar to an Internet Service Provider, is a distributor (and not a publisher) of content supplied by third parties and Users. Accordingly, Dcount Now has no more editorial control over such content than does a public library, bookstore or newsstand. Any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, or any other Users are those of the respective author(s) or distributors and not of Dcount Now. Neither Dcount Now nor any third-party provider of information guarantees the accuracy, completeness, or usefulness of any content, nor its merchantability or fitness for any particular purpose (refer to Section 14 above for the complete provisions governing limitation of liabilities and disclaimers of warranty). In many instances, the content available through this Website represents the opinions and judgments of the respective information provider, User, or other user not under contract with Dcount Now. Dcount Now neither endorses nor is responsible for the accuracy or reliability of any opinion, advice or statement made on the Website by anyone other than authorized Dcount Now employee spokespersons while acting in official capacities. Under no circumstances will Dcount Now be liable for any loss or damage caused by User's reliance on information obtained through the Website. It is the responsibility of User to evaluate the accuracy, completeness or usefulness of any information, opinion, advice etc. or other content available through the Website. The Website contains links to third party Websites maintained by other content providers. These links are provided solely as a convenience to you and not as an endorsement by Dcount Now of the contents on such third-party sites and Dcount Now hereby expressly disclaims any representations regarding the content or accuracy of materials on such third-party Web sites. If User decides to access linked third-party Web sites, User does so at own risk. Unless you have executed a written agreement with Dcount Now expressly permitting you to do so, you may not provide a hyperlink to the Website from any other website. Dcount Now reserves the right to revoke its consent to any link at any time in its sole discretion. </p>


<h4>Force Majeure</h4>
<p>Without prejudice to any other provision herein, Dcount Now shall not be liable for any loss, damage or penalty as a result of any delay in or failure to deliver or otherwise perform hereunder due to any cause beyond the Dcount Now's control, including, without limitation, acts of the User, embargo or other governmental act, regulation or request affecting the conduct of Dcount Now's business, fire, explosion, accident, theft, vandalism, riot, acts of war, strikes or other labour difficulties, lightning, flood, windstorm or other acts of God. </p>


<h4>Miscellaneous</h4>
<p>This Agreement and any operating rules for the Website established by Dcount Now constitute the entire agreement of the parties with respect to the subject matter hereof. No waiver by either party of any breach or default hereunder is a waiver of any preceding or subsequent breach or default. The section headings used herein are for convenience only and shall be of no legal force or effect. If any provision of this Agreement is held invalid by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions contained in this Agreement and the remaining portions of this Agreement shall continue in full force and effect. The failure of either party to exercise any of its rights under this Agreement shall not be deemed a waiver or forfeiture of such rights or any other rights provided hereunder. </p>
<p>Dcount Now's headquarters are in lucknow, India. Legal issues arising out of, but not exclusive to the use of, this Website or the Minisites (unless otherwise specifically stated) are governed by and in accordance with the laws of Lucknow (exclusive of its rules regarding conflicts of laws). </p>



		    <!---->
		</div>
					<!-- /contact-info -->
				</div>
			</div>
		</div>
		<br>

	</section>
